export const ANALYSIS_CONFIG = {
  pullRequestWindowDays: 90,
  staleIssueThresholdDays: 30,
  maxPullRequestsAnalyzed: 200,
  maxIssuesAnalyzed: 200,
  cacheTtlMinutes: 15,
  commitWindowWeeks: 12,
  maxCommitsListed: 200,
  maxCommitDetailsAuthenticated: 60,
  maxCommitDetailsUnauthenticated: 20,
  maxFileHotspots: 10,
  maxContributorRows: 10,
  maxReleasesAnalyzed: 30,
  releaseTrendMonths: 12,
  minimumRemainingRateLimit: 10,
  ciWindowDays: 90,
  maxWorkflowRunsAnalyzed: 100,
  maxWorkflowsAnalyzed: 30,
  maxWorkflowFilesRead: 20,
  maxRepositoryTreeEntriesUsed: 100_000,
  maxEvidencePathsPerSignal: 5,
  minimumCompletedRunsForReliableCiRate: 5,
  healthScoreVersion: "v1"
} as const;
